- name: datatypes of ansible
  hosts: local
  connection: local
  vars:
    Course: "DevSecops with AWS" # this is string
    DURATION: 120 # this is number
    islive: true #boolean
    tools: #Lists[]
    - ansible
    - git
    - Prometheus
    concepts: #map or object or dictionary{}
      CI: jenkins
      Scripting: Linux, Shell, Ansible, Terraform, Python
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: " COURSE: {{Course}}, DURATION: {{DURATION}}, islive: {{islive}}, TOOLS: {{tools}}, CONCEPTS:{{concepts}}"

