- name: creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysqlll
    - frontend
    - backend
    sg_id: sg-08364b85f92f4ead4
    subnet_id: subnet-0aef76ed6b9bd21bb
    
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      image_id: ami-09c813fb71547fc4f
      tags:
       name: "{{ item }}"
    loop: "{{ instances }}"