# - name: functions
#   hosts: local
#   connection: local
#   tasks:
#   - name: check undefined variable
#     ansible.builtin.debug:
#       msg: "Hello,{{ person | default ('ramesh') }}"


# - name: functions
#   hosts: local
#   connection: local
#   vars:
#     persons: "Ramesh,Suresh,Mahesh,Ganesh"
#   tasks:
#   - name: check undefined variables
#     ansible.builtin.debug:
#       msg: "Hello,{{ person | default ('ramesh') }}"

#   - name: check undefined variables
#     ansible.builtin.debug:
#       msg: "Hello,{{persons}} "


- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Mahesh,Ganesh"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello,{{ person | default ('ramesh') }}"

  - name: split function
    ansible.builtin.debug:
      msg: "Hello,{{persons | split(',')}} "


  - name: convert map into list
    vars:
      course:
        name: "devsecops"
        duration: 10hrs
        trainer: shiva
    ansible.builtin.debug:
      msg: "course info: {{course | dict2items}}"