# - name: loops
#   hosts: local
#   connection: local
#   tasks:
#   - name: looping in ansible
#     ansible.builtin.debug:
#       msg: "{{item}}"

#     loop:
#     - suresh
#     - mahesh
#     - ramesh


- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing packages on ansible
    ansible.builtin.package:
      name: "{{item}}"
      state: installed

    loop:
    - nginx
    - mysql
    - mongodb

