- name: experimenting
  hosts: local
  connection: local
  tasks:
  - name: ansible modules under a single task
    ansible.builtin.debug:
      msg: "Hello iam from task1 with debug module"
      
    # ansible.builtin.file:
    #   path: /app
    #   state: directory
    # ansible.builtin.user:
    #   name: roboshop
    #   system: true
    #   shell: /sbin/nologin
    #   home: /app
