- name: vars ranking in ansible
  hosts: local
  connection: local
  vars:
    GREETING: "HELLO FROM PLAY1"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: enter the GREETING
    private: false
  tasks:
  - name: greeting from task1
    vars:
      GREETING: "Hello from task1"
    ansible.builtin.debug:
      msg: "Hello {{GREETING}} "
    

# 1. Args
# 2.