- name: vars ranking in ansible
  hosts: local
  connection: local
  vars:
    GREETING: "HELLO FROM PLAY1"
  vars:
  - course.yaml
  vars_prompt:
  - name: USERNAME
    prompt: enter the username
    private: false
  tasks:
  - name: greeting from task1
    ansible.builtin.debug:
      msg: "Hello from {{USERNAME}}"
    