- name: play variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course information from task1
    ansible.builtin.debug:
      msg: " Hello this Course is: {{ COURSE }}, Course duration is: {{DURATION}}, Trainer is: {{TRAINER}} "
  
  

